### ISSUE TITLE
모든 라우터에서 반복되는 설정을 최상단으로 끌어올리는 것을 제안

### ISSUE THREAD

**Issue by autroshot** [aquaman122/book_store_project#3]
대부분의 라우터에서 반복되는 `router.use(express.json())`과 `require("dotenv").config()`를 최상단인 `app.js`에서 설정하는 것이 좋을 것 같습니다.

`router.use(express.json())`은 `app.use(express.json())`으로 변경할 수 있습니다.

**Comment by aquaman122** [comment]
감사합니다
